-- Create a database schema for student grade system. It contains student data and their grade of each subject based on the different semester.
CREATE TABLE STUDENTSDATA(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
DOB DATE NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE SUBJECTS(
ID INT NOT NULL AUTO_INCREMENT,
SUBJECT_NAME VARCHAR(30) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE SEMESTERS(
ID INT NOT NULL AUTO_INCREMENT,
SEMESTER_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE GRADES(
ID INT NOT NULL AUTO_INCREMENT,
StudentID INT NOT NULL,
SubjectID INT NOT NULL,
SemesterID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (StudentID) REFERENCES STUDENTSDATA(ID),
FOREIGN KEY (SubjectID) REFERENCES SUBJECTS(ID),
FOREIGN KEY (SemesterID) REFERENCES SEMESTERS(ID)
);