-- Create a database structure for students and its college. One student can be on one college only
CREATE TABLE STUDENTS(
ID INT NOT NULL AUTO_INCREMENT,
STUDENT_NAME VARCHAR(30) NOT NULL,
AGE INT NOT NULL,
COLLEGE_ID INT NOT NULL UNIQUE,
PRIMARY KEY(ID),
FOREIGN KEY(COLLEGE_ID) REFERENCES COLLEGE(ID)
);

CREATE TABLE COLLEGE(
ID INT NOT NULL AUTO_INCREMENT,
COLLEGE_NAME VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);